name: cocktailr
description: Find delicious cocktails based on the ingredients you have!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Used for consuming HTTP requests.
  http: ^0.12.0+2

  # Used for dependency injection.
  provider: ^3.0.0+1

  # Used for additional stream functionality.
  rxdart: ^0.22.1

  # Used for caching data.
  sqflite: ^1.1.6+3

  # Used to support sqflite.
  path_provider: ^1.2.0

  # Used for icons that iOS users are familiar with (default dependency).
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
